version: '2'
services:

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./server
    expose:
      - 3001
    ports:
      - "3001:3001"
    links:
      - mongo  
    volumes:
      - ./server:/usr/src/app/src/
      
  client:
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/public:/usr/src/app/public
    build: ./client
    ports:
      - "3000:3000"
    links:
      - server 